---
# What components to install
install_postgresql: true
install_pgpool: true
# Common settings
eng_messages: true  # This is actual when the OS locale is not English. If you want error messages to be in English then set to - true. In this case, the english OS locale will be installed, the LANG environment variable and the lc_messages postgresql parameter will be set.
# Firewall
remove_firewall: false  # Set to true to remove firewall from OS
setup_firewall: true  # Do you want to configure firewall (port settings)?
