---
become: yes
become_method: sudo
gather_facts: yes

vars_files:
  - main_vars.yml

- hosts: postgresql
    roles:
      - name: postgresql
        when: install_postgresql
- hosts: pgpool
    - name: pgpool
      when: install_pgpool
# DEBUG
tasks:
  - name: Show facts available on the system
    ansible.builtin.debug:
      var: 
        # - ansible_facts
        - ansible_facts['os_family']
        - ansible_facts['distribution']
        - ansible_facts['distribution_major_version']
