---
- name: Install postgresql
  become: yes
  become_method: sudo
  gather_facts: yes
  hosts: postgresql
  vars_files:
    - secret_vars.yml
  roles:
    - name: postgresql
      when: install_postgresql

- name: Install pgpool
  become: yes
  become_method: sudo
  gather_facts: yes
  hosts: pgpool
  vars_files:
    - secret_vars.yml
  roles:
    - name: pgpool
      when: install_pgpool
