---
- name: Install en_US.UTF-8 locale if needed
  locale_gen:
    name: en_US.UTF-8
    state: present
  when: eng_messages

- name: Install required packages
  apt:
    name:
      - python-apt
    state: present
