---
- name: Install en_US.UTF-8 locale if needed
  locale_gen:
    name: en_US.UTF-8
    state: present
  when: eng_messages


# package dialog for fix:
#   debconf: не удалось инициализировать интерфейс: Dialog
#   debconf: (Ни одна из dialog-подобных программ не установлена, поэтому вы не можете использовать dialog-интерфейс. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
#   debconf: будет использован интерфейс: Readline
- name: Install required packages
  apt:
    name:
      - python-apt
      - dialog
      - apt-utils
    state: present
